# 测试环境自定义配置（本地调试+远程UAT用）
# 与application.yml合并覆盖
spring:
  datasource.system:
    url: jdbc:mysql://127.0.0.1:3306/talkweb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: talkweb
    password: talkweb
  # redis配置
  redis:
    host: 47.104.21.117
    port: 6787
    password: talkedu@,2017
# 日志配置
logging:
  level:
    org:
      mybatis: ERROR
      springframework: ERROR
    com:
      atomikos: ERROR
      talkedu: DEBUG
    de.codecentric.boot.admin: ERROR
  file: /home/webapp/logs/talkedu-card/runtime.log
